# Generated by Django 4.2.10 on 2024-02-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilingo_app', '0006_alter_wordinen_alphabet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishalphabet',
            name='image',
            field=models.ImageField(default='', upload_to='alphabet/en/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='russianalphabet',
            name='image',
            field=models.ImageField(default='', upload_to='alphabet/ru/', verbose_name='Изображение'),
        ),
    ]
