# Generated by Django 5.0.2 on 2024-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilingo_app', '0007_alter_englishalphabet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(default='', upload_to='themes/', verbose_name='Изображение темы'),
        ),
    ]
